### ISSUE TITLE
Deleted arxiv + zbmath items

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/docker-importer#131]
35 items that had an arxiv ID and a zbmath ID were deleted and have to be reuploaded. The QIDs are ['Q85487', 'Q89551', 'Q92243', 'Q96449', 'Q96450', 'Q98645', 'Q106023', 'Q104117', 'Q106322', 'Q58729', 'Q133720', 'Q136862', 'Q159635', 'Q159675', 'Q161299', 'Q161308', 'Q161312', 'Q161316', 'Q141549', 'Q144808', 'Q151777', 'Q147832', 'Q150754', 'Q151509', 'Q151900', 'Q112152', 'Q110204', 'Q122338', 'Q119768', 'Q119892', 'Q121136', 'Q128141', 'Q128731', 'Q129044', 'Q131099']

**Comment by eloiferrer** [comment]
I was able to restore the initial arxiv versions with 'undelete' now. For the arXiv side this is done now.

**Comment by LizzAlice** [comment]
Ok, zbmath is also done
