### ISSUE TITLE
Item gets duplicated because importer does not find that it exists

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/docker-importer#149]
https://portal.mardi4nfdi.de/wiki/Item:Q6483261

I am not sure why this happens yet, I am suspecting that it is because of special characters, but I could not find the reason yet.

**Comment by LizzAlice** [comment]
It might be related to the fact that we search for the label using `bytes(label, "utf-8")` in https://github.com/MaRDI4NFDI/importer-api/blob/main/server/search.py

**Comment by LizzAlice** [comment]
When searching for the label, we are searching in wbt_text, where it is saved in the wbx_text column, which is a ``wbx_text` varbinary(255) NOT NULL`. The length of the label in `bytes(label, "utf-8")` is 266, so it is too long. However, on the portal, the label is shown in full, so it might be saved in two places? Do you know more about this @physikerwelt ?

**Comment by LizzAlice** [comment]
For reference, the title is:
`Kitāb al-Manāẓir. The optics of Ibn al-Haytham. Books I--III. On direct vision. Volume 1. Translation. Volume 2. Introduction, commentary, glossaries, concordance, indices. Translated from the Arabic and with a preface, introduction and commentary by A. I. Sabra`
When converted using the bytes function, it is `b'Kit\xc4\x81b al-Man\xc4\x81\xe1\xba\x93ir. The optics of Ibn al-Haytham. Books I--III. On direct vision. Volume 1. Translation. Volume 2. Introduction, commentary, glossaries, concordance, indices. Translated from the Arabic and with a preface, introduction and commentary by A. I. Sabra'`
In the table, it is `Kitāb al-Manāẓir. The optics of Ibn al-Haytham. Books I--III. On direct vision. Volume 1. Translation. Volume 2. Introduction, commentary, glossaries, concordance, indices. Translated from the Arabic and with a preface, introduction and commentary by`

**Comment by physikerwelt** [comment]
I guess it would be better to search for the DE number, titles are also sometimes changed by editors in zbMATH. So I would go with the DE number first

**Comment by physikerwelt** [comment]
Can you explain how why you search in wbt_text. I looked at the table, and for example it finds wbx_id `6897614` for `wbx_text LIKE '%49687'`

All the documentation on the table I found in the code is

```
Stores a record per text value that are used in different terms in different languages.
Part of the \ref md_docs_storage_terms storage system.
```
The actual data displayed on the site is stored in json.

**Comment by LizzAlice** [comment]
Because we use that table to search for labels of items, as in the function I linked above. This usually works, except that in this case, the label seems to have been cut off

**Comment by physikerwelt** [comment]
I mean how would you use wbx_id?

**Comment by LizzAlice** [comment]
It is used inside the join operation

**Comment by physikerwelt** [comment]
where can I find the join details?

**Comment by LizzAlice** [comment]
In the function I linked above

**Comment by physikerwelt** [comment]
The actual data, which is in the text table is:
```
{"type":"item","id":"Q6483261","labels":{"en":{"language":"en","value":"Kit\u0101b al-Man\u0101\u1e93ir. The optics of Ibn al-Haytham. Books I--III. On direct vision. Volume 1. Translation. Volume 2. Introduction, commentary, glossaries, concordance, indices. Translated from the Arabic and with a preface, introduction and commentary by A. I. Sabra"}},"descriptions":{"en":{"language":"en","value":"scientific article; zbMATH DE number 49687"}},"aliases":[],"claims":{"P31":[{"mainsnak":{"snaktype":"value","property":"P31","hash":"fd5912e4dab4b881a8eb0eb27e7893fef55176ad","datavalue":{"value":{"entity-type":"item","numeric-id":56887,"id":"Q56887"},"type":"wikibase-entityid"}},"type":"statement","id":"Q6483261$AC739A10-C739-4B44-86A8-E0338B371587","rank":"normal"}],"P159":[{"mainsnak":{"snaktype":"value","property":"P159","hash":"60719ef1d8d60471bee0fe036fcbd4a46a411bba","datavalue":{"value":{"text":"Kit\u0101b al-Man\u0101\u1e93ir. The optics of Ibn al-Haytham. Books I--III. On direct vision. Volume 1. Translation. Volume 2. Introduction, commentary, glossaries, concordance, indices. Translated from the Arabic and with a preface, introduction and commentary by A. I. Sabra","language":"en"},"type":"monolingualtext"}},"type":"statement","id":"Q6483261$97770F5C-2280-4423-934B-A8BE0DBEC1B3","rank":"normal"}],"P225":[{"mainsnak":{"snaktype":"value","property":"P225","hash":"98b666baec1d084a3a56511f1b7f389c66694a9e","datavalue":{"value":"1520.01027","type":"string"}},"type":"statement","id":"Q6483261$F9D74385-941F-4ABB-B199-760984332D77","rank":"normal"}],"P16":[{"mainsnak":{"snaktype":"value","property":"P16","hash":"97bc7cea65b9018424366fdf5be90cf24de6de40","datavalue":{"value":{"entity-type":"item","numeric-id":3281904,"id":"Q3281904"},"type":"wikibase-entityid"}},"type":"statement","id":"Q6483261$C4E2CA79-DEAD-4667-8284-03B2F020427E","rank":"normal"}],"P200":[{"mainsnak":{"snaktype":"value","property":"P200","hash":"46b30fefd991094b60eda4ec146d0df3c6473e9a","datavalue":{"value":{"entity-type":"item","numeric-id":6483260,"id":"Q6483260"},"type":"wikibase-entityid"}},"type":"statement","id":"Q6483261$6A198A6C-1788-473B-A7D1-ECA0703FD013","rank":"normal"}],"P28":[{"mainsnak":{"snaktype":"value","property":"P28","hash":"993fc9c82f14e8095667589a94f8558bb2df341f","datavalue":{"value":{"time":"+0001-01-01T00:00:00Z","timezone":0,"before":0,"after":0,"precision":11,"calendarmodel":"http:\/\/www.wikidata.org\/entity\/Q1985727"},"type":"time"}},"type":"statement","id":"Q6483261$C762CCFE-A1EC-4501-9C7D-4B87D153DA5F","rank":"normal"}],"P226":[{"mainsnak":{"snaktype":"value","property":"P226","hash":"6d1ec52031732a7dc8db0752c0fcd99128394879","datavalue":{"value":"01A75","type":"string"}},"type":"statement","id":"Q6483261$6A5641AA-B6ED-4682-9476-CCFEC29D6F16","rank":"normal"},{"mainsnak":{"snaktype":"value","property":"P226","hash":"8284164a1e7f35e5df7a37db4dab808a8ec438b6","datavalue":{"value":"01A30","type":"string"}},"type":"statement","id":"Q6483261$3FF1EA87-4650-4CFD-961A-1582E5103FC5","rank":"normal"}],"P1451":[{"mainsnak":{"snaktype":"value","property":"P1451","hash":"b5a050291b004f2cf89ed402404982757784a369","datavalue":{"value":"49687","type":"string"}},"type":"statement","id":"Q6483261$17B7AEC8-5A89-487C-BEAF-728C19473596","rank":"normal"}],"P1460":[{"mainsnak":{"snaktype":"value","property":"P1460","hash":"57f7fea50d2ce1b39b695c4a1313582eed405e38","datavalue":{"value":{"entity-type":"item","numeric-id":5976449,"id":"Q5976449"},"type":"wikibase-entityid"}},"type":"statement","id":"Q6483261$1260006B-0B59-44AF-94F7-D42E11A93D0A","rank":"normal"}]},"sitelinks":[]}
```
This should explain why the title is displayed correctly on the page, etc

**Comment by eloiferrer** [comment]
Can you describe how you got that cell of information (table name, etc)?
The function above is based on the tables described here: https://doc.wikimedia.org/Wikibase/master/php/docs_storage_terms.html which are apparently redundant and not even complete (since they contain truncated labels).

**Comment by physikerwelt** [comment]
I guess it's a problem with your bytes function. You could debug if the resulting query is equivalent to
```
SELECT t.*
         FROM my_wiki.wbt_text t
         WHERE wbx_text = 'Kitāb al-Manāẓir. The optics of Ibn al-Haytham. Books I--III. On direct vision. Volume 1. Translation. Volume 2. Introduction, commentary, glossaries, concordance, indices. Translated from the Arabic and with a preface, introduction and commentary by'
         ORDER BY wbx_text
```
which works well.

**Comment by physikerwelt** [comment]
> Can you describe how you got that cell of information (table name, etc)?

Something like
```SQL
SELECT old_text from page
         JOIN revision on page_id = rev_page
         JOIN content on rev_sha1 = content_sha1
         JOIN text on old_id = Substr(content_address,4)
         where page_title = 'Q6483261'
```

while there are certainly better ways to get the text.

**Comment by LizzAlice** [comment]
The problem is that we don't have the qid. We want to get the qid based on the label. However, as long labels are cut in the table we used for searching (wbt_text), this fails in some cases. So we would need another table where the text is not cut to get out the QID. Or we need to make the table column larger

**Comment by LizzAlice** [comment]
Why is it called "old_text"? Does that mean it might be outdated?

**Comment by physikerwelt** [comment]
> Why is it called "old_text"? Does that mean it might be outdated?

Yeah, the idea is to eventually store the data directly in a triple store. However, this is not implemented yet.

**Comment by physikerwelt** [comment]
> And also, do you know if there is some parameter in the conf to make the table column larger @physikerwelt ?

No, it might be. However, why don't you use the haswbstatement to search for IDs?

**Comment by LizzAlice** [comment]
The problem was that sometimes it took quite long to index with elasticsearch. So if you upload a lot of items and need to check if they are there immediately afterwards, which can happen, they might not be shown yet. However, in the sql table, they get shown immediately. So it would just be easier to increase the column size (or use another table).

**Comment by LizzAlice** [comment]
Querying the text table is really slow though, so maybe not that one

**Comment by LizzAlice** [comment]
Ok, maybe the solution is to only search for the longest possible label subset if it is too long. That might create a few edge cases, but not many

**Comment by physikerwelt** [comment]
> The problem was that sometimes it took quite long to index with elasticsearch. So if you upload a lot of items and need to check if they are there immediately afterwards, which can happen, they might not be shown yet. However, in the sql table, they get shown immediately. So it would just be easier to increase the column size (or use another table).

The question is how much time you want to spend on this. I checked https://www.mediawiki.org/wiki/Extension:WikibaseQualityConstraints but unfortunately, it has the same problems as querying es. I would suggest to force running es updates before the next update.

**Comment by LizzAlice** [comment]
> Ok, maybe the solution is to only search for the longest possible label subset if it is too long. That might create a few edge cases, but not many

I think I'll just rewrite the function like this, that shouldn't take too long.

**Comment by physikerwelt** [comment]
If you use haswbstatement the only thing you have to worry about is items that have been inserted in the last seconds. If it is save to assume that there is only one inserter running, maybe keeping the latest updates in memory might be option. (This is what I did in my importer)

**Comment by LizzAlice** [comment]
It is possible that several importers are running at the same time. Also, there were issues in the past where elasticsearch slowed down drastically which lead to many duplicates.

**Comment by physikerwelt** [comment]
if nothing else works we can update the table math_wbs_entity_map 
```SQL
create table my_wiki.math_wbs_entity_map
(
    math_local_qid        int                                   not null
        primary key,
    math_external_id      int                                   not null,
    math_external_id_type int                                   not null,
    math_timestamp        timestamp default current_timestamp() null on update current_timestamp(),
    constraint math_external_id_type
        unique (math_external_id_type, math_external_id)
)
    charset = `binary`;

**Comment by LizzAlice** [comment]
What does that table have to do with where the label is stored?

**Comment by physikerwelt** [comment]
That table was used by an importer I wrote to keep track of what id's already have been inserted. We could update it, and do the bookkeeping there. The SQL constraint ensures, that there can be only one QID for a given external identifier. However, that would be quite a bit of work.

**Comment by LizzAlice** [comment]
I think it would be easier to just cut the string, there shouldn't be many cases that are longer than that and have the exact same substring

**Comment by LizzAlice** [comment]
fixed
