### ISSUE TITLE
Build the docker-importer as container with CI and enable it in portal-compose.

### ISSUE THREAD

**Issue by Hyper-Node** [MaRDI4NFDI/docker-importer#19]
- [x]  Copy CI workflow 
- [x] Check that build is successfull
- [x] Check if a cronjob is running already on the built container and enable functionality to toggle it with env var. 
- [x] Check that the python implentations are installed.

**Comment by LizzAlice** [comment]
There is a cronjob that executes import.sh; however, that file does not contain any commands yet
