### ISSUE TITLE
Add metrics exporter for Grafana

### ISSUE THREAD

**Issue by dajuno** [MaRDI4NFDI/docker-importer#55]
The importers should dump metrics that can be visualized by Prometheus/Grafana.

For instance:
- number of imported entities (per import)
- total number of entities
- date/time of import
- performance metrics: time, size of data?

@LizzAlice let's discuss

**Comment by eloiferrer** [comment]
Just some thoughts on this, in preparation for a discussion.

1) Number of imported entities per import: We can save this information as the entities get created or we could also perform a SPARQL query before and after the import. We could also show which type of entities we are creating (e.g. X new publications, Y new authors, etc.) based on the 'instance of' statement.

2) Total number of entities: Maybe the easiest way is also to repeat a SPARQL query at a given interval.

3) Date/time import: I am not sure I understand how we want to present this information. Is this the time for a given import (e.g. CRAN packages globally) or the time each specific entity got created?

4) Haven't found a neat way to find the knowledge graph size, apart from calculating it from the mediawiki file size before and after import. 

We need to clarify if we want to save the relevant info in a file that is then read by grafana or if we want to save the data in a SQL table. Or if there is another preferred approach.

**Comment by eloiferrer** [comment]
Wikibase metrics are now shown directly in the portal through SPARQL queries and not through grafana.
Issue can be reopened if we decide to directly show Grafana dashboards to the public.
