### ISSUE TITLE
Insert Wikibase QID/PID on WikibaseImport entities

### ISSUE THREAD

**Issue by eloiferrer** [MaRDI4NFDI/docker-importer#57]
- Properties and Items imported using WikibaseImport should be completed with a statement indicating their original ID in Wikidata.
- This could be done after WikibaseImport finishes with a script that reads the wbs_entity_mapping sql table and creates the corresponding statements.

**Comment by Hyper-Node** [comment]
Is this related to an epic ?

**Comment by eloiferrer** [comment]
This has been implemented in the new solution using WikibaseIntegrator (https://github.com/MaRDI4NFDI/docker-importer/pull/68)
