### ISSUE TITLE
Switch from Wikibase Importer to Wikibase Integrator

### ISSUE THREAD

**Issue by LizzAlice** [MaRDI4NFDI/docker-importer#61]
**Epic description in words**:
The Wikibase Importer is lacks desired functionalities, such as importing statements and property values. Thus, the plan is to switch to the Wikibase Integrator.

 
**Issues**: 
- [x] fix entity/property.write() not working
  - [x] reproduce error
  - [x] try to find working format using WikibaseIntegrator code
- [x] get id from insert
- [x] method for checking if entity already exists
- [x] method for writing
- [x] method for updating
- [x] update database with wikidata id and local id
- [x] add claims to primary items
- [x] include wikidata id as claim when importing data from wikidata
- [x] set user agent when interacting with wikidata
- [x] permanently install wikibaseintegrator package in docker
- [ ] restructure code
- [ ] write tests
- [x] Remove WikibaseImport extension from docker-wikibase

**Comment by eloiferrer** [comment]
Switch complete with the new WikibaseIntegrator
